<?php
$scripts = array(
    'labor' => array('lab', 'labajax'),
    'infra' => array('infra22'),
    'infraensino' => array('infraensino'),
    'ensinofund' => array('ensinofund1'),
    'ensinomedio' => array('ensinomedio'),
    'prodsaude' => array('psaude'),
    'produto' => array('farmajax', 'farma'),
    'prodsaude4' => array('prod4ajax3', 'saude'),
    'homologar' => array('homologacao')
);

$sessao = $_SESSION["sessao"];

if(isset($_POST["inputAnobase"])){
	$sessao->setAnobase($_POST["inputAnobase"]);	
}
$anobase = $sessao->getAnobase();
$nomeUnidade = $sessao->getNomeUnidade();
$codunidade = $sessao->getCodUnidade();
$usuario = $sessao->getResponsavel();

?>

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="pt-br">
<head>
  <link rel="shortcut icon" href="webroot/img/sinpeg.png" />
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SINPEG </title>

  
  <!-- Cabeçalho jquery e bootstrap adicionado 16/01/2023 -->
  <script type="text/javascript" src="webroot/js/jquery-ui-1.10.3/js/jquery-3.6.3.min.js"></script>
  <script type="text/javascript" src="webroot/js/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.js"></script>
  <script src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"></script>

  <!-- Bootstrap 4 -->
  <script src="novo_layout/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="novo_layout/dist/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes <script src="novo_layout/dist/js/demo.js"></script>-->	

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="novo_layout/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="novo_layout/dist/css/adminlte.min.css">

  <!-- DataTables -->
  <link rel="stylesheet" href="novo_layout/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="novo_layout/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <link rel="stylesheet" href="novo_layout/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
  
  <script src="https://www.gstatic.com/charts/loader.js"></script>

  <?php
  // carrega sob demanda os arquivos javascript 
  // de acordo com o módulo e ação informada
  if (isset($_GET['modulo'])) {
      if (isset($scripts[$_GET['modulo']])) {
          foreach ($scripts[$_GET['modulo']] as $sc) {
              $string = '<script type="text/javascript" src="webroot/js/' . $sc . '.js"></script>';
              echo $string;
          }
      }
  }
  // fim
  ?>

  <link rel="stylesheet" type="text/css" href="webroot/css/modulo.css">
</head>
<body class="hold-transition sidebar-mini" >
<div class="wrapper">
 <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="webroot/img/sinpeg.png" alt="SinpegLogo" >
  </div>
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link"><?php echo $codunidade; ?> - <?php echo $nomeUnidade; ?></a>
      </li>      
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <form id="formAnobase" action="#" method="post">
			
			<div class="col-3 text-center">		
			   
<input name="inputAnobase" class='form-control datepicker' style="font-size: 10pt; width:60px;" onclick="ocultar()" maxlength="4" size="4" value= " <?php echo $anobase;?>" id="datepickerYear"/>
			</div>
		</form>	
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="novo_layout/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="novo_layout/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="novo_layout/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    
    <div align="center" style="padding:5px;">
      <a href="index.php">
        <img src="webroot/img/sinpeg.png" alt="Sinpeg Logo" width="120px" height="52px" style="margin:auto;">
      </a>
    </div>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="novo_layout/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <!-- verificar -->
          <a href="index.php?modulo=usuario&acao=altusuario" class="d-block"><?php echo $usuario ?></a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
			   
			<?php  require 'menu.php'; ?>          
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">    
	


    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
       
		<?php if (isset($flashes)): ?>
                    <div class="alert alert-success" >
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <?php foreach ($flashes as $flash): ?>
                            <strong><?php echo $flash; ?></strong>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <?php if (isset($erros)): ?>
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <?php foreach ($erros as $erro): ?>
                            <strong><?php echo $erro; ?></strong>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <?php
                if ($template != null) {
                    require $template;
                }
                ?>
            
          
        
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Sistema Integrado de Planejamento e Gestão
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; <a href="https://proplan.ufpa.br">PROPLAN</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->
  <link rel="stylesheet" type="text/css" href="webroot/js/jquery-ui-1.13.2/jquery-ui.css">

  <!--App Antigo-->
  <!--<script type="text/javascript" src="webroot/js/jquery-3.2.1.min.js"></script>-->
    <script type="text/javascript" src="webroot/js/main.js"></script>
    <script type="text/javascript" src="webroot/js/usajax1.js"></script>
    <script type="text/javascript" src="webroot/js/usajax2.js"></script>
    <script type="text/javascript" src="webroot/js/relatorios.js"></script>
    <script type="text/javascript" src="webroot/js/pdi.js"></script>

    <script type="text/javascript" src="webroot/js/high-charts/highcharts.js"></script>
    <script type="text/javascript" src="webroot/js/exporting.js"></script>
    <script type="text/javascript" src="webroot/js/bootstrap.js"></script>
    <script type="text/javascript" src="webroot/js/materialize.js"></script>
    <script type="text/javascript" src="webroot/js/jquery.mask.js"></script> 
    <script type="text/javascript" src="webroot/js/epolo.js"></script>
    <script type="text/javascript" src="webroot/js/raa.js"></script>     
    <script type="text/javascript" src="webroot/js/editarPainel.js"></script>

    <script  src="webroot/js/modal_index.js"></script>
    
  
    <!--<script type="text/javascript" src="webroot/js/jquery-ui-1.10.3/js/jquery-1.9.1.js"></script>
    <script type="text/javascript" src="webroot/js/jquery-ui-1.10.3/js/jquery-ui-1.10.3.custom.js"></script>-->
   <!-- <script type="text/javascript" src="vendors/tablesorter/js/jquery.tablesorter.min.js"></script>
    <script type="text/javascript" src="vendors/tablesorter/js/jquery.tablesorter.widgets.min.js"></script>
    <script type="text/javascript" src="vendors/tablesorter/addons/pager/jquery.tablesorter.pager.js"></script>
    <link rel="stylesheet" type="text/css" href="vendors/tablesorter/addons/pager/jquery.tablesorter.pager.css"> -->

    <style>
      .tablesorter-pager .btn-group-sm .btn {
        font-size: 1.2em; /* make pager arrows more visible */
      }
    </style>
    
    <link rel="stylesheet" type="text/css" href="webroot/css/multi-select.css">
    <script src="webroot/js/jquery.multi-select.js"></script>
    <script src="webroot/js/jquery.quicksearch.js"></script>

    <!-- Arquivos do editor -->                  	
    <!--<script src="webroot/js/summernote.js"></script>
    <script type="text/javascript" src="webroot/js/summernote-cleaner.js"></script>-->

    <!-- include summernote css/js atualizado -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>


    <script type='text/javascript'>
      $(function(){
          $('#datepickerYear').datepicker({
            changeMonth: false,
              changeYear: true,        
              showButtonPanel: true,
              yearRange: '2018:2030',
              dateFormat: 'yy',
              onClose: function(dateText, inst) { 		        
            }
          });
      });


      function atualizaAno(){
        $('#datepickerYear').val($('.ui-datepicker-year').val());
        $("#formAnobase").submit();	
      }

      $('#datepickerYear').on({
        click: function () {
          $(".ui-datepicker-calendar").hide();
            $(".ui-datepicker-month").hide();
            $(".ui-datepicker-current").hide();
            $(".ui-icon-circle-triangle-w").hide();
            $(".ui-icon-circle-triangle-e").hide();
            $('.ui-datepicker-year').attr('onChange', 'selectAno();');
            $('.ui-datepicker-close').attr('onClick', 'atualizaAno();');
            //$('.ui-datepicker-year').val($('#datepickerYear').val());
            $( '.ui-datepicker-title' ).css( 'color','black' );	      	     
          }
      
            
      });
      
      function selectAno(){
        $(".ui-datepicker-calendar").hide();
          $(".ui-datepicker-month").hide();
          $(".ui-datepicker-current").hide();
          $(".ui-icon-circle-triangle-w").hide();
          $(".ui-icon-circle-triangle-e").hide();
          $('.ui-datepicker-year').attr('onChange', 'selectAno();');
          $('.ui-datepicker-close').attr('onClick', 'atualizaAno();');
          $( '.ui-datepicker-title' ).css( 'color','black' );	
      }
    </script>

    <!-- ChartJS -->
    <script src="novo_layout/plugins/chart.js/Chart.min.js"></script>

    <!-- bs-custom-file-input -->
    <script src="novo_layout/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    
    <!-- DataTables  & Plugins -->
    <script src="novo_layout/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="novo_layout/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="novo_layout/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="novo_layout/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="novo_layout/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="novo_layout/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="novo_layout/plugins/jszip/jszip.min.js"></script>
    <script src="novo_layout/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="novo_layout/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="novo_layout/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="novo_layout/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="novo_layout/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
  </body>
</html>
